src/Entity/CitySearch.php
<?php

namespace App\Entity;

use App\Entity\City;
use Doctrine\ORM\Mapping as ORM;

class CitySearch
{

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\City")
     */
    private $City;


    public function getCity(): ?City
    {
        return $this->City;
    }

    public function setCity(?City $City): self
    {
        $this->City = $City;

        return $this;
    }
}

src/Controller/SearchController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Entity\CitySearch;
use App\Entity\PrixSearch;
use App\Form\CitySearchType;
use App\Form\PrixSearchType;
use App\Repository\ArticlesRepository;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use App\Entity\CategoriesSearch;
use App\Form\CategoriesSearchType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SearchController extends AbstractController
{
    /**
     * @Route("/searchcat/", name="article_par_cat")
     * Method({"GET", "POST"})
     */
    public function articlesParCategorie(Request $request) {
        $CategoriesSearch = new CategoriesSearch();
        $form = $this->createForm(CategoriesSearchType::class,$CategoriesSearch);
        $form->handleRequest($request);
  
        $articles= [];
  
        if($form->isSubmitted() && $form->isValid()) {
          $Categories = $CategoriesSearch->getCategories();
         
          if ($Categories!="") 
          {
            
            $articles= $Categories->getArticles();
           // ou bien 
           //$articles= $this->getDoctrine()->getRepository(Article::class)->findBy(['Categories' => $Categories] );
          }
          else   
            $articles= $this->getDoctrine()->getRepository(Articles::class)->findAll();
          }
        
        return $this->render('search/articleParCategorie.html.twig',['form' => $form->createView(),'articles' => $articles]);
    }

    /**
     * @Route("/searchcity/", name="article_par_city")
     * Method({"GET", "POST"})
     */
    public function articlesParCity(Request $request) {
        $CitysSearch = new CitySearch();
        $form = $this->createForm(CitySearchType::class,$CitysSearch);
        $form->handleRequest($request);
  
        $articles= [];
  
        if($form->isSubmitted() && $form->isValid()) {
          $City = $CitysSearch->getCity();
         
          if ($City!="") 
          {
            
            $articles= $City->getArticles();
           
          }
          else   
            $articles= $this->getDoctrine()->getRepository(Articles::class)->findAll();
          }
        
        return $this->render('search/articleParCity.html.twig',['form' => $form->createView(),'articles' => $articles]);
    }

    /**
     * @Route("/searchprix/", name="article_par_prix")
     * Method({"GET"})
     */
    public function articlesParPrix(Request $request,ArticlesRepository $articleRepo)
    {
     
      $prixSearch = new PrixSearch();
      $form = $this->createForm(PrixSearchType::class,$prixSearch);
      $form->handleRequest($request);

      $articles= [];

      if($form->isSubmitted() && $form->isValid()) {
        $minPrix = $prixSearch->getMinPrix(); 
        $maxPrix = $prixSearch->getMaxPrix();
          
       $articles= $articleRepo->findByPrixRange($minPrix,$maxPrix);
        //$articles= $this->getDoctrine()->getRepository(Articles::class)->findByPrixRange($minPrix,$maxPrix);
    }

    return  $this->render('search/articlesParPrix.html.twig',[ 'form' =>$form->createView(), 'articles' => $articles]);  
  }
}

templates/search/articleParCategorie.html.twig
{% extends 'base.html.twig' %}
{% block title%} Liste des Articles par Status{% endblock %}

{% block body %}
<style>
    body{
        background-image: url("https://lavozdemotul.com/wp-content/uploads/2016/08/registration-page-background-504-1.png");
        background-size: 100% 700px;
        
       
    }
     img{
        height:200px;
        width:220px;
    }
</style>

    <h1 class="text-center" style="color:#CD5C5C;font-weight:bold; font-family:cursive">Rechercher Articles Par Status</h1><i class="d-flex justify-content-center"><hr class="col-md-6" style="color:#800000;font-weight:bold;height:2px;width:94%"></i>

<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-md-7" style="margin-top:20px" >
            {{ form_start(form) }}

            <div >
            
            {{ form_row(form.Categories) }}
            
                <button type="submit" class="btn btn-success" style="font-family:cursive">Rechercher</button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>    
</div>
<div class="container" style="margin-top: 20px">
    <div class="row">
        
        {% for article in articles %}
            <div class="col-6" style="margin-top: 20px">
                <div class="card text-center">
                    <div class="card-header">
                        <i style="font-family:bold;">{{article.titre}}    </i>
                    </div>
                    <div class="card-body">
                        <img class="justify-content-center col-11 img-fluid rounded" style="filter: drop-shadow(0 0 0.75rem #F5F5DC);height:260px" src="{{asset('/uploads/images/articles/' ~ article.image )}}" alt="image">
                        
                        <p><i style="color:blue;">Prix:</i> {{article.prix}} DT</p> 
                        <p><i style="color:blue;">Status:</i> {{ article.categorie }}  </p>
                        <p><i style="color:blue;">lieu:</i> {{ article.city }}  </p>
                        
                    </div>
                    <div class="card-footer text-muted">
                        <p>
                        {% if is_granted('ROLE_USER') %}
                        <a href="{{ path('articles_show', {'id': article.id}) }}" style="font-family:cursive;" class="btn btn-primary">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                            Voir plus
                        </a>
                        {% endif %}
                        {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('articles_edit', {'id': article.id}) }}" style="font-family:cursive;" class="btn btn-success">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                            Modifier
                        </a>
                        {% endif %}
                        {% if is_granted('ROLE_ADMIN') %}
                        
                        <a href="{{path('articles_delete', {'id': article.id})}}" style="font-family:cursive;" class="btn btn-danger" onclick="return confirm('Etes-vous sûr de supprimer cet article?');">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                            Supprimer
                        </a>
                        {% endif %}
                        </p>
                    </div>
                </div>
            </div>    
        
    {% else %}
    <p style="font-family:cursive;" class="text-center">
    <img src='https://t3.ftcdn.net/jpg/02/95/34/72/360_F_295347201_ZQfeqTU03fWOUOGq87M3ShBCJx9Vrn9G.jpg'  alt="oop pas d'articles"/><br>
    Aucun articles disponible pour le moment, merci de nous visiter ultérieurment.</p>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/search/articleParCity.html.twig
{% extends 'base.html.twig' %}
{% block title%} Liste des Articles par Ville{% endblock %}

{% block body %}
<style>
    body{
        background-image: url("https://lavozdemotul.com/wp-content/uploads/2016/08/registration-page-background-504-1.png");
        background-size: 100% 700px;
        
       
    }
    img{
        height:200px;
        width:220px;
    }
</style>
    <h1 class="text-center" style="color:#CD5C5C;font-weight:bold; font-family:cursive">Rechercher Articles Par Régions</h1><i class="d-flex justify-content-center"><hr class="col-md-6" style="color:#800000;font-weight:bold;height:2px;width:94%"></i>
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-md-7" style="margin-top:20px" >
            {{ form_start(form) }}
            <div >
               {{ form_row(form.City) }}
                <button type="submit" class="btn btn-success" style="font-family:cursive">Rechercher</button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>    
</div>


 <div class="container" style="margin-top: 20px">
    <div class="row">
        
        {% for article in articles %}
            <div class="col-6" style="margin-top: 20px">
                <div class="card text-center">
                    <div class="card-header">
                        <i style="font-family:bold;">{{article.titre}}    </i>
                    </div>
                    <div class="card-body">
                        <img class="justify-content-center col-11 img-fluid rounded" style="filter: drop-shadow(0 0 0.75rem #F5F5DC);height:260px" src="{{asset('/uploads/images/articles/' ~ article.image )}}" alt="image">
                        
                        <p><i style="color:blue;">Prix:</i> {{article.prix}} DT</p> 
                        <p><i style="color:blue;">Status:</i> {{ article.categorie }}  </p>
                        <p><i style="color:blue;">lieu:</i> {{ article.city }}  </p>
                        
                    </div>
                    <div class="card-footer text-muted">
                        <p>
                        {% if is_granted('ROLE_USER') %}
                        <a href="{{ path('articles_show', {'id': article.id}) }}" style="font-family:cursive;" class="btn btn-primary">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                            Voir plus
                        </a>
                        {% endif %}
                        {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('articles_edit', {'id': article.id}) }}" style="font-family:cursive;" class="btn btn-success">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                            Modifier
                        </a>
                        {% endif %}
                        {% if is_granted('ROLE_ADMIN') %}
                        
                        <a href="{{path('articles_delete', {'id': article.id})}}" style="font-family:cursive;" class="btn btn-danger" onclick="return confirm('Etes-vous sûr de supprimer cet article?');">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                            Supprimer
                        </a>
                        {% endif %}
                        </p>
                    </div>
                </div>
            </div>    
        
    {% else %}
    <p style="font-family:cursive;" class="text-center">
    <img src='https://t3.ftcdn.net/jpg/02/95/34/72/360_F_295347201_ZQfeqTU03fWOUOGq87M3ShBCJx9Vrn9G.jpg'  alt="oop pas d'articles"/><br>
    Aucun articles disponible pour le moment, merci de nous visiter ultérieurment.</p>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/search/articlesParPrix.html.twig
{% extends 'base.html.twig' %}
{% block title%} Liste des Articles par prix{% endblock %}

{% block body %}
<style>
    body{
        background-image: url("https://lavozdemotul.com/wp-content/uploads/2016/08/registration-page-background-504-1.png");
        background-size: 100% 700px;
        
       
    }
    img{
        height:200px;
        width:220px;
    }
</style>
    <h1 class="text-center" style="color:#CD5C5C;font-weight:bold; font-family:cursive">Rechercher Articles Par Prix</h1><i class="d-flex justify-content-center"><hr class="col-md-6" style="color:#800000;font-weight:bold;height:2px;width:94%"></i>
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-md-7" style="margin-top:20px" >
              {{ form_start(form) }}
            <div >
                {{ form_row(form.minPrix) }}
                {{ form_row(form.maxPrix) }}
                <button type="submit" class="btn btn-success" style="font-family:cursive">Rechercher</button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>    
</div>

<div class="container" style="margin-top: 20px">
    <div class="row">
        
        {% for article in articles %}
            <div class="col-6" style="margin-top: 20px">
                <div class="card text-center">
                    <div class="card-header">
                        <i style="font-family:bold;">{{article.titre}}    </i>
                    </div>
                    <div class="card-body">
                        <img class="justify-content-center col-11 img-fluid rounded" style="filter: drop-shadow(0 0 0.75rem #F5F5DC);height:260px" src="{{asset('/uploads/images/articles/' ~ article.image )}}" alt="image">
                        
                        <p><i style="color:blue;">Prix:</i> {{article.prix}} DT</p> 
                        <p><i style="color:blue;">Status:</i> {{ article.categorie }}  </p>
                        <p><i style="color:blue;">lieu:</i> {{ article.city }}  </p>
                        
                    </div>
                    <div class="card-footer text-muted">
                        <p>
                        {% if is_granted('ROLE_USER') %}
                        <a href="{{ path('articles_show', {'id': article.id}) }}" style="font-family:cursive;" class="btn btn-primary">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                            Voir plus
                        </a>
                        {% endif %}
                        {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('articles_edit', {'id': article.id}) }}" style="font-family:cursive;" class="btn btn-success">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                            Modifier
                        </a>
                        {% endif %}
                        {% if is_granted('ROLE_ADMIN') %}
                        
                        <a href="{{path('articles_delete', {'id': article.id})}}" style="font-family:cursive;" class="btn btn-danger" onclick="return confirm('Etes-vous sûr de supprimer cet article?');">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                            Supprimer
                        </a>
                        {% endif %}
                        </p>
                    </div>
                </div>
            </div>    
        
    {% else %}
    <p style="font-family:cursive;" class="text-center">
    <img src='https://t3.ftcdn.net/jpg/02/95/34/72/360_F_295347201_ZQfeqTU03fWOUOGq87M3ShBCJx9Vrn9G.jpg'  alt="oop pas d'articles"/><br>
    Aucun articles disponible pour le moment, merci de nous visiter ultérieurment.</p>
    {% endfor %}
    </div>
</div>
{% endblock %}